coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
      api:
        flags:
          - api
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  api:
    paths:
      - api/

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: false
